# Generated by Django 5.0.1 on 2024-02-05 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.pdfdocument')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.pdfdocument')),
            ],
        ),
    ]
